"use client";
/* OAuth login is a full document navigation to establish secure cookies. */
/* eslint-disable @next/next/no-html-link-for-pages */
import { createContext, useContext, useMemo, useState, type RefObject } from "react";
import type { CatalogGame } from "../lib/catalog";
import type { NewsArticle } from "../lib/news";
import { articleCategories, articlePlatforms, categoryLabels, ipTimeline, type Franchise, type NewsCategory } from "../lib/franchises";
import { useIP } from "./ip-provider";
import { useIPArchive } from "../lib/use-ip-registry";
import { EmptyState, Icon } from "./ui";
import { mergeCatalog } from "../lib/catalog";
import { useSeriesChannel } from "../lib/use-series-channel";
import { SeriesChronology } from "./series-chronology";

export const IPNavigation = createContext<((id: string) => void) | null>(null);
export function IPLink({ ip }: { ip: Franchise }) {
  const navigate = useContext(IPNavigation);
  return <a className={`ip-tag ip-${ip.color}`} href={`/?view=ip&ip=${ip.id}`} title={`${ip.ja} · ${ip.en}`} onClick={(event) => { if (navigate && !event.ctrlKey && !event.metaKey && !event.shiftKey && event.button === 0) { event.preventDefault(); navigate(ip.id); } }}>{ip.name}<IPBadge ip={ip}/><span aria-hidden="true">↗</span></a>;
}
export function IPBadge({ ip }: { ip: Franchise }) { return <>{ip.discovered && <small className="ip-trend new">新识别 IP</small>}{ip.rising && <small className="ip-trend rising">飙升 IP</small>}</>; }
function sortedIPs(items: Franchise[], sort: string) {
  const field = sort === "games" ? "gameCount" : sort === "updated" ? "updatedAt" : "newsCount";
  // Host-default collation differs between Cloudflare and the user's browser;
  // use a deterministic tie-break so the initial HTML hydrates without errors.
  return [...items].sort((a, b) => (b[field] || 0) - (a[field] || 0) || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}
function IPSort({ value, change }: { value: string; change: (value: string) => void }) { return <label className="ip-sort">系列排序 <select value={value} onChange={(e) => change(e.target.value)}><option value="news">资讯量</option><option value="games">作品数量</option><option value="updated">最近更新</option></select></label>; }
export function FollowIP({ ip, compact = false }: { ip: Franchise; compact?: boolean }) {
  const store = useIP(); const following = store.following.includes(ip.id);
  return <button className={`button ip-follow ${following ? "followed" : ""} ${compact ? "compact" : ""}`} disabled={store.busy || store.loading} aria-pressed={following} aria-label={`${following ? "取消关注" : "关注"}${ip.name}`} onClick={() => store.follow(ip.id)}><Icon name={following ? "check" : "plus"}/>{following ? "已关注" : "关注"}</button>;
}
export function IPTags({ items, follow = false }: { items: Franchise[]; follow?: boolean }) {
  if (!items.length) return null;
  return <div className="ip-tags" aria-label="关联 IP（来源文本与实体关系识别）">{items.map((ip) => <span className="ip-tag-group" key={ip.id}><IPLink ip={ip}/>{follow && <FollowIP ip={ip} compact/>}</span>)}</div>;
}
export function PopularIPs({ value, onChange }: { value: string; onChange: (id: string) => void }) {
  const { franchises, franchiseById, registryState, refreshRegistry } = useIP(); const [sort, setSort] = useState("news");
  const popular = sortedIPs(franchises, sort).slice(0, 16);
  return <><div className="ip-quick"><span>热门 IP<small>动态频道</small></span><IPSort value={sort} change={setSort}/><div className="ip-scroll" role="group" aria-label="IP 快捷筛选"><button aria-pressed={value === "all"} className={value === "all" ? "active" : ""} onClick={() => onChange("all")}>全部系列</button>{popular.map((ip) => <button key={ip.id} aria-pressed={value === ip.id} className={value === ip.id ? "active" : ""} onClick={() => onChange(ip.id)}>{ip.name}<IPBadge ip={ip}/></button>)}</div>{value !== "all" && franchiseById(value) && <IPLink ip={franchiseById(value)!}/>}</div>{registryState === "error" && <div className="notice" role="status">动态词库暂不可用，正在展示上次可用分类。<button onClick={() => void refreshRegistry()}>重试</button></div>}</>;
}
export function IPSearch({ query, onChange, catalog, inputRef }: { query: string; onChange: (value: string) => void; catalog: CatalogGame[]; inputRef: RefObject<HTMLInputElement | null> }) {
  const [focused, setFocused] = useState(false); const [active, setActive] = useState(-1); const navigate = useContext(IPNavigation);
  const { suggestFranchises } = useIP();
  const suggestions = useMemo(() => suggestFranchises(query, catalog), [query, catalog, suggestFranchises]); const open = focused && suggestions.length > 0;
  return <div className="ip-search-wrap" onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setFocused(false); }}><div className="global-search"><Icon name="search"/><input ref={inputRef} role="combobox" aria-label="搜索游戏、别名或 IP 系列" aria-autocomplete="list" aria-expanded={open} aria-controls={open ? "ip-suggestions" : undefined} aria-activedescendant={open && active >= 0 ? `ip-suggestion-${active}` : undefined} value={query} onFocus={() => setFocused(true)} onChange={(event) => { onChange(event.target.value); setActive(-1); setFocused(true); }} onKeyDown={(event) => {
    if (event.key === "Escape") { setFocused(false); setActive(-1); }
    if (open && ["ArrowDown", "ArrowUp"].includes(event.key)) { event.preventDefault(); setActive((current) => event.key === "ArrowDown" ? (current + 1) % suggestions.length : (current - 1 + suggestions.length) % suggestions.length); }
    if (open && event.key === "Enter" && active >= 0 && !event.nativeEvent.isComposing) { event.preventDefault(); navigate?.(suggestions[active].id); setFocused(false); setActive(-1); }
  }} placeholder="搜索中 / 日 / 英名称、TotK 或系列"/><kbd>Ctrl K</kbd>{query && <button aria-label="清除搜索" onClick={() => onChange("")}><Icon name="close"/></button>}</div>{open && <div className="ip-suggestion-panel"><p>优先探索关联 IP 频道</p><div id="ip-suggestions" role="listbox" aria-label="关联 IP 频道">{suggestions.map((ip, index) => <button id={`ip-suggestion-${index}`} role="option" aria-selected={active === index} className={active === index ? "active" : ""} tabIndex={-1} key={ip.id} onMouseDown={(e) => e.preventDefault()} onClick={() => { navigate?.(ip.id); setFocused(false); setActive(-1); }}><span className={`ip-monogram ip-${ip.color}`}>{ip.name.slice(0, 1)}</span><span><strong>{ip.name}</strong><small>{ip.ja} · {ip.en}</small></span><Icon name="arrow"/></button>)}</div><small>↑ ↓ 选择频道 · Enter 打开 · Esc 收起</small></div>}</div>;
}
export function IPFacets({ games, query, value, onChange }: { games: CatalogGame[]; query: string; value: string; onChange: (id: string) => void }) {
  const { gameFranchises, franchises } = useIP();
  const counts = new Map<string, number>(); games.forEach((game) => gameFranchises(game).forEach((ip) => counts.set(ip.id, (counts.get(ip.id) || 0) + 1)));
  const involved = franchises.filter((ip) => counts.has(ip.id));
  return <aside className="ip-facets" aria-label="搜索结果 IP 筛选"><h2>关联系列</h2><p>在本次搜索结果中收窄范围</p><button className={value === "all" ? "active" : ""} onClick={() => onChange("all")}>全部结果 <span>{games.length}</span></button>{involved.map((ip) => <button key={ip.id} className={value === ip.id ? "active" : ""} aria-pressed={value === ip.id} onClick={() => onChange(ip.id)}>{ip.name}<span>{counts.get(ip.id)}</span></button>)}{!involved.length && <p>“{query}” 的结果暂未识别到已收录 IP。</p>}<p className="ip-disclaimer">仅依据名称与别名归类；不表示作品已被官方确认。</p></aside>;
}
export function IPNewsCard({ item }: { item: NewsArticle }) {
  const { articleFranchises } = useIP();
  return <article><div className="news-card-meta"><span className={`source-tag ${item.sourceKind}`}>{item.sourceKind === "official" ? "官方" : "媒体"} · {item.sourceName}</span><span>{item.language}</span></div><h2><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a></h2><IPTags items={articleFranchises(item)} follow/>{item.topic !== "news" && <span className="news-topic">{item.topic === "rumor" ? "传闻 / 爆料 · 未经官方证实" : "访谈"}</span>}{item.excerpt && <p>{item.excerpt}…</p>}<div className="news-card-platforms">{articlePlatforms(item).map((platform) => <span key={platform}>{platform}</span>)}</div><footer><time dateTime={item.publishedAt}>{new Date(item.publishedAt).toLocaleString("zh-CN", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}</time><a href={item.url} target="_blank" rel="noreferrer">阅读原文<Icon name="external"/></a></footer></article>;
}
export function IPNewsFeed({ items, loading = false, empty = "暂无匹配的动态" }: { items: NewsArticle[]; loading?: boolean; empty?: string }) {
  const [page, setPage] = useState(1); const pages = Math.max(1, Math.ceil(items.length / 12)); const current = Math.min(page, pages);
  return <>{items.length ? <div className="news-list live-news-list">{items.slice((current - 1) * 12, current * 12).map((item) => <IPNewsCard key={item.id} item={item}/>)}</div> : <EmptyState title={loading ? "正在获取动态…" : empty} description="当前来源没有匹配内容；可以切换筛选或稍后刷新。不会为了填满栏目而生成新闻。"/>}{pages > 1 && <nav className="pagination" aria-label="IP 动态分页"><button className="button" disabled={current === 1} onClick={() => setPage(current - 1)}>上一页</button><span>{current} / {pages} · {items.length} 条</span><button className="button" disabled={current === pages} onClick={() => setPage(current + 1)}>下一页</button></nav>}</>;
}
export function IPNewsStatus() {
  const { news } = useIP();
  return <><div className="news-health"><span>{news.feed ? `最近抓取 · ${new Date(news.feed.fetchedAt).toLocaleString("zh-CN")}` : "正在读取中日英新闻源…"}</span><button className="text-button" disabled={news.state === "loading"} onClick={() => void news.refresh()}>刷新新闻</button></div>{(news.state === "error" || news.feed?.stale) && <div className="notice" role="status">新闻暂时无法更新，缓存内容不代表最新资讯。<button onClick={() => void news.refresh()}>重试</button></div>}{news.feed?.sources.some((item) => !item.ok) && <div className="notice">部分来源暂不可用：{news.feed.sources.filter((item) => !item.ok).map((item) => item.name).join("、")}。当前数量可能不完整。</div>}</>;
}
export function IPDirectory({ catalog }: { catalog: CatalogGame[] }) {
  const { franchises, gameFranchises, engine, registryState, refreshRegistry } = useIP(); const [sort, setSort] = useState("games"); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [level,setLevel]=useState("all"); const [platform,setPlatform]=useState("all");
  const items = sortedIPs(franchises.filter((ip) => [ip.name, ip.ja, ip.en, ...ip.aliases, ...(ip.searchAliases||[])].join("\n").normalize("NFKC").toLowerCase().includes(query.normalize("NFKC").toLowerCase().trim())&&(level==="all"||(level==="root"?!ip.parentIds?.length:!!ip.parentIds?.length))&&(platform==="all"||ip.platforms?.some(p=>platform==="Nintendo"?/Nintendo|Switch|Game Boy|Wii|GameCube|NES|DS/i.test(p):platform==="PlayStation"?/PlayStation|PS[1-5]|PSP|Vita/i.test(p):platform==="Xbox"?/Xbox/i.test(p):p==="PC"))), sort);
  const pages = Math.max(1, Math.ceil(items.length / 24)); const current = Math.min(page, pages);
  return <><div className="page-heading"><div><p className="eyebrow">THE FRANCHISE LIBRARY</p><h1>探索游戏系列</h1><p>从初代到最新作。按平台、主系列与子系列，找到下一个想探索的世界。</p></div><button className="button" onClick={() => void refreshRegistry()}>刷新目录</button></div>
  <div className="ip-engine-health" role="status"><strong>{registryState === "loading" ? "正在读取系列目录…" : registryState === "error" ? "目录更新暂不可用，保留已有内容" : "公共目录 · 离线更新"}</strong>{engine && <span>{engine.channels.toLocaleString()} 个系列频道 · {engine.works?.toLocaleString()} 部作品 · {engine.characters?.toLocaleString()} 位已关联角色 · 目录核对：{engine.updatedAt?.slice(0,10)}</span>}<span>Cloudflare 高频抓取已关闭。公共资料预先生成，账号与私人记录仍保存在云端。</span></div>
  <div className="status-tabs" role="group" aria-label="系列层级">{[["all","全部频道"],["root","主系列"],["child","子系列"]].map(([id,name])=><button key={id} className={level===id?"active":""} aria-pressed={level===id} onClick={()=>{setLevel(id);setPage(1);}}>{name}</button>)}</div>
  <div className="news-toolbar"><label>查找系列 <input type="search" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="炼金工房、亚兰德、Kirby…"/></label><label>平台家族<select value={platform} onChange={e=>{setPlatform(e.target.value);setPage(1);}}>{["all","Nintendo","PlayStation","Xbox","PC"].map(p=><option key={p} value={p}>{p==="all"?"所有平台":p}</option>)}</select></label><IPSort value={sort} change={(v) => { setSort(v); setPage(1); }}/><span>{items.length} 个频道</span></div>
  <div className="ip-directory">{items.slice((current - 1) * 24, current * 24).map((ip) => <article key={ip.id}><div className="series-card-top"><span className={"ip-monogram ip-" + ip.color}>{ip.name.slice(0, 1)}</span><span>{ip.firstYear||"年代待补充"}{ip.lastYear&&ip.lastYear!==ip.firstYear?" — "+ip.lastYear:""}</span></div><h2><IPLink ip={ip}/></h2><p className="ip-names"><span lang="ja">{ip.ja || "日文名待来源补充"}</span><span lang="en">{ip.en || "英文名待来源补充"}</span></p><p>{ip.description}</p><div className="series-branches">{ip.parentIds?.length?"子系列频道":"主系列频道"}{!!ip.childIds?.length&&" · "+ip.childIds.length+" 个子系列"}</div><footer><small>{ip.gameCount??catalog.filter((game) => gameFranchises(game).some((match) => match.id === ip.id)).length} 部已索引 · {ip.newsCount ?? 0} 篇资讯</small><FollowIP ip={ip}/></footer></article>)}</div>
  {!items.length && <EmptyState title="没有匹配的系列" description="尝试中日英其他名称，或取消平台与层级筛选；目录尚有未补齐的作品。"/>}
  {pages > 1 && <nav className="pagination" aria-label="IP 频道分页"><button className="button" disabled={current === 1} onClick={() => setPage(current - 1)}>上一页</button><span>{current} / {pages}</span><button className="button" disabled={current === pages} onClick={() => setPage(current + 1)}>下一页</button></nav>}
  <p className="catalog-footnote">建档条件：明确系列关系及至少两部非重制 / 合集作品，不再要求新闻热度。关联依据官方资料与 Wikidata 实体关系；三语名称保留来源原文，知识库译名不等同于官方译名。索引数量不代表已完成全作品核验。</p></>;
}
export function IPHub({ id, catalog, onOpen, onBack }: { id: string; catalog: CatalogGame[]; onOpen: (game: CatalogGame) => void; onBack: () => void }) {
  const { news, franchiseById, gameFranchises, articleFranchises } = useIP(); const archive = useIPArchive(id); const history=useSeriesChannel(id); const ip = franchiseById(id); const [category, setCategory] = useState<NewsCategory>("latest"); const [platform, setPlatform] = useState("all"); const [language, setLanguage] = useState("all");
  const allGames = useMemo(() => mergeCatalog(catalog.filter((game) => gameFranchises(game).some((match) => match.id === id)),history.channel?.games||[]), [catalog, id, gameFranchises,history.channel]);
  const games = allGames.filter((game) => platform === "all" || game.platforms.includes(platform)); const timeline = ipTimeline(games);
  const allNews = (archive.items.length ? archive.items : news.feed?.items || []).filter((item) => articleFranchises(item).some((match) => match.id === id));
  const items = allNews.filter((item) => articleCategories(item).includes(category) && (platform === "all" || articlePlatforms(item).includes(platform)) && (language === "all" || item.language === language));
  if (!ip) return <EmptyState title="未找到这个 IP 频道" description="此系列尚未进入站内分类表。" action={<button className="button" onClick={onBack}>浏览全部 IP</button>}/>;
  return <><button className="text-button ip-back" onClick={onBack}>← 全部 IP 频道</button><section className={`ip-hub-header ip-${ip.color}`}><div className="ip-hub-heading"><span className={`ip-monogram ip-${ip.color}`}>{ip.name.slice(0, 1)}</span><div><p className="eyebrow">IP CHANNEL</p><h1>{ip.name} <IPBadge ip={ip}/></h1><p className="ip-names"><span lang="ja">{ip.ja}</span><span lang="en">{ip.en}</span></p></div><FollowIP ip={ip}/></div><p>{ip.description}</p><div className="ip-hub-stats"><span><strong>{allGames.length}</strong>已索引作品</span><span><strong>{ipTimeline(allGames).length}</strong>待发售版本 / 计划</span><span><strong>{ip.newsCount ?? archive.total}</strong>已归档资讯</span><a href={ip.sourceUrl} target="_blank" rel="noreferrer">{ip.entityId ? "系列识别来源" : "系列官方资料"} <Icon name="external"/></a></div></section>
    <div className="ip-tags">{ip.parentIds?.map(parent=>{const value=franchiseById(parent);return value?<span key={parent}>所属主系列 <IPLink ip={value}/></span>:null;})}{ip.childIds?.map(child=>{const value=franchiseById(child);return value?<IPLink key={child} ip={value}/>:null;})}</div>
    <div className="news-toolbar"><label>平台 <select value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="all">全部历史平台</option>{[...new Set(allGames.flatMap(g=>g.platforms))].sort().map((value) => <option key={value}>{value}</option>)}</select></label><span>新闻平台按原文提及筛选；年表包含旧主机与新平台。</span></div>
    <section className="ip-release-section"><div className="section-heading"><h2>接下来的发售计划</h2><span>日期保留原始精度</span></div>{timeline.length ? <ol className="ip-timeline">{timeline.map((release, index) => <li key={`${release.game.id}-${index}`}><time>{release.date || release.label || "日期未定"}</time><div><button className="text-button" onClick={() => onOpen(release.game)}>{release.game.title}</button><small>{release.platforms.join(" · ") || "平台待确认"} · {release.kind}</small><a href={release.sourceUrl} target="_blank" rel="noreferrer">核对来源 ↗</a></div></li>)}</ol> : <p className="ip-empty-inline">当前索引没有符合平台条件的未来计划。不把旧日期当成新作，也不推测未宣布的续作。</p>}</section>
    <SeriesChronology key={id+platform} ip={ip} games={games} onOpen={onOpen} loading={history.state==="loading"} error={history.state==="error"} retry={history.retry}/>
    <div className="section-heading"><h2>系列动态</h2><span>中 / 日 / 英</span></div><IPNewsStatus/><div className="status-tabs" role="group" aria-label="IP 动态分类">{Object.entries(categoryLabels).map(([key, label]) => <button key={key} aria-pressed={category === key} className={category === key ? "active" : ""} onClick={() => setCategory(key as NewsCategory)}>{label}<small>{allNews.filter((item) => articleCategories(item).includes(key as NewsCategory)).length}</small></button>)}</div><div className="news-toolbar"><label>语言 <select value={language} onChange={(e) => setLanguage(e.target.value)}><option value="all">全部语言</option>{["中文", "日文", "英文"].map((value) => <option key={value}>{value}</option>)}</select></label><span>{items.length} 条匹配 / 已载入 {allNews.length} 条 · 分类依据标题关键词</span></div><IPNewsFeed key={`${id}-${category}-${platform}-${language}`} items={items} loading={news.state === "loading"}/>{archive.more && <button className="button ip-archive-more" disabled={archive.state === "loading"} onClick={() => void archive.loadMore()}>{archive.state === "loading" ? "正在读取历史…" : "载入更早资讯（共 " + archive.total + " 篇）"}</button>}{archive.state === "error" && <div className="notice">历史资讯读取失败。<button onClick={() => void archive.loadMore()}>重试</button></div>}<p className="catalog-footnote">关联标签依据来源文本与实体知识库，可能遗漏。资讯中提及 IP 不代表官方合作；媒体与传闻不改变游戏的已核实发售资料。</p>
  </>;
}
export function FollowingFeed({ query }: { query: string }) {
  const store = useIP(); const { articleFranchises, matchesNewsQuery, franchiseById, franchises } = store; const [ip, setIP] = useState("all"); const [platform, setPlatform] = useState("all");
  const items = (store.news.feed?.items || []).filter((item) => articleFranchises(item).some((match) => store.following.includes(match.id) && (ip === "all" || ip === match.id)) && (platform === "all" || articlePlatforms(item).includes(platform)) && matchesNewsQuery(item, query));
  if (!store.user) return <EmptyState title="为自己定制一份游戏动态" description="登录后关注喜欢的 IP，只看与你有关的消息；关注列表和通知已读状态可跨设备同步。" action={<a className="button primary" href="/api/auth/login">使用 GitHub 登录</a>}/>;
  if (store.loading) return <EmptyState title="正在读取云端关注…" description="正在加载你的 IP 订阅。"/>;
  return <><div className="following-intro"><h2>我的关注 <small>{store.following.length} 个系列</small></h2><p>只展示所关注系列的抓取资讯。来源约每 3 小时抓取；页面每 5 分钟检查已发布快照。</p></div>{store.following.length ? <><div className="ip-followed-list">{store.following.map((id) => { const value = franchiseById(id); return value ? <span className="ip-tag-group" key={id}><IPLink ip={value}/><FollowIP ip={value} compact/></span> : null; })}</div><div className="news-toolbar"><label>系列 <select value={ip} onChange={(e) => setIP(e.target.value)}><option value="all">全部关注</option>{store.following.map((id) => <option key={id} value={id}>{franchiseById(id)?.name}</option>)}</select></label><label>平台 <select value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="all">全部平台</option>{["Switch", "Switch 2", "PS5", "PC", "Xbox"].map((value) => <option key={value}>{value}</option>)}</select></label><span>{items.length} 条匹配</span></div><IPNewsStatus/><IPNewsFeed key={`${query}-${ip}-${platform}-${store.following.join(",")}`} items={items} loading={store.news.state === "loading"}/></> : <><p className="ip-empty-inline">还没有关注系列。从下面选几个喜欢的世界开始。</p><div className="ip-followed-list">{sortedIPs(franchises, "news").slice(0,24).map((ip) => <span className="ip-tag-group" key={ip.id}><IPLink ip={ip}/><FollowIP ip={ip} compact/></span>)}</div></>}</>;
}
export function NotificationCenter() {
  const store = useIP(); const { franchiseById } = store;
  return <><div className="page-heading"><div><p className="eyebrow">YOUR SIGNALS</p><h1>通知中心 <small>{store.unread} 未读</small></h1><p>关注后的发售计划更新与新预告，保留最近 30 天；不推送传闻。</p></div><div className="backup-actions"><button className="button" disabled={!store.user || store.busy} onClick={() => void store.refreshNotifications()}>检查新动态</button><button className="button" disabled={!store.user || store.busy || !store.unread} onClick={() => void store.markRead()}>全部标为已读</button></div></div>{!store.user ? <EmptyState title="登录后查看你的提醒" description="通知跟随 GitHub 账号保存，不与其他用户共享。" action={<a className="button primary" href="/api/auth/login">使用 GitHub 登录</a>}/> : store.notifications.length ? <div className="ip-notifications">{store.notifications.map((item) => <article key={item.id} className={item.readAt ? "" : "unread"}><div><span className="source-tag">{item.reason}</span><small>{item.article.sourceKind === "official" ? "官方公告" : "媒体报道 · 以官方确认为准"} · {item.article.sourceName}</small><time>{new Date(item.createdAt).toLocaleString("zh-CN")}</time></div><h2><a href={item.article.url} target="_blank" rel="noreferrer" onClick={() => { if (!item.readAt && !store.busy) void store.markRead([item.id]); }}>{item.article.title}<Icon name="external"/></a></h2><IPTags items={item.ipIds.map(franchiseById).filter((ip): ip is Franchise => !!ip)}/><button className="text-button" disabled={!!item.readAt || store.busy} onClick={() => void store.markRead([item.id])}>{item.readAt ? "已读" : "标为已读"}</button></article>)}</div> : <EmptyState title={store.loading ? "正在读取通知…" : "暂时没有新提醒"} description="不会用关注前的旧文章打扰你。新发布的重大动态会在下次站内检查时出现在这里。"/>}<p className="catalog-footnote">站内检查在页面打开时运行；关闭网站期间不发送浏览器推送或邮件。重新打开时补查最近归档资讯；后台会持续抓取，来源未开放或抓取失败时可能遗漏。列表最多展示最近 200 条。</p></>;
}
