"use client";
import { useRef, useState, type Dispatch, type SetStateAction, type ReactNode } from "react";
import { signals, SNAPSHOT_DATE } from "../data/games";
import { curatedGames, LIBRARY_KEY, localDate, matchesQuery, releaseLabels, releaseState, validateLibrary, type CatalogFeed, type CatalogGame, type Library } from "../lib/catalog";
import { EmptyState, Icon } from "./ui";
const platforms = ["PC", "PS5", "PS4", "Switch 2", "Switch", "Xbox", "iOS", "Android"];
export function CalendarView({ catalog, query, onOpen, onUndated }: { catalog: CatalogGame[]; query: string; onOpen: (game: CatalogGame) => void; onUndated: () => void }) {
  const [month, setMonth] = useState(localDate().slice(0, 7)); const [day, setDay] = useState<string | null>(null); const [platform, setPlatform] = useState("all");
  const events = catalog.flatMap((game) => game.releases?.length ? game.releases.map((release, i) => ({ ...game, id: `${game.id}-release-${i}`, releaseDate: release.date, dateLabel: release.label, platforms: release.platforms, declaredStatus: (release.date && release.date <= game.source.checkedAt ? "released" : "upcoming") as CatalogGame["declaredStatus"], parentId: game.id })) : [{ ...game, parentId: game.id }]);
  const games = events.filter((game) => game.releaseDate?.startsWith(month) && (platform === "all" || game.platforms.includes(platform)) && matchesQuery(game, query)).sort((a, b) => a.releaseDate!.localeCompare(b.releaseDate!));
  const [year, index] = month.split("-").map(Number); const first = new Date(year, index - 1, 1); const count = new Date(year, index, 0).getDate(); const offset = (first.getDay() + 6) % 7;
  const shift = (step: number) => { setMonth(localDate(new Date(year, index - 1 + step, 1)).slice(0, 7)); setDay(null); }; const selected = day ? games.filter((game) => game.releaseDate === day) : games;
  return <><div className="page-heading"><div><p className="eyebrow">RELEASE CALENDAR</p><h1>发售日历</h1><p>查看每个月的发售安排，把期待留给值得玩的游戏。</p></div><button className="button" onClick={() => { setMonth(localDate().slice(0, 7)); setDay(null); }}>回到本月</button></div><div className="calendar-toolbar"><div><button className="icon-button" aria-label="上个月" onClick={() => shift(-1)}>‹</button><h2>{new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "long" }).format(first)}</h2><button className="icon-button" aria-label="下个月" onClick={() => shift(1)}>›</button></div><label><span className="sr-only">日历平台</span><select value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="all">全部平台</option>{platforms.map((item) => <option key={item}>{item}</option>)}</select></label><span>{games.length} 部游戏</span></div>
    <div className="calendar-board"><div className="weekdays">{["一", "二", "三", "四", "五", "六", "日"].map((label) => <span key={label}>周{label}</span>)}</div><div className="calendar-grid">{Array.from({ length: offset + count }, (_, i) => { const dateNumber = i - offset + 1; if (dateNumber <= 0) return <div className="calendar-pad" key={i}/>; const date = `${month}-${String(dateNumber).padStart(2, "0")}`; const releases = games.filter((game) => game.releaseDate === date); return <button key={date} className={`calendar-day ${date === localDate() ? "today" : ""} ${day === date ? "selected" : ""}`} onClick={() => setDay(day === date ? null : date)} aria-label={`${date}，${releases.length} 部游戏`} aria-pressed={day === date}><b>{dateNumber}</b><span className="day-releases">{releases.slice(0, 2).map((game) => <span key={game.id}>{game.title}</span>)}{releases.length > 2 && <small>还有 {releases.length - 2} 部</small>}</span>{releases.length > 0 && <i className="mobile-day-count">{releases.length}</i>}</button>; })}</div></div>
    <div className="section-heading"><h2>{day ? `${day.slice(5).replace("-", "月")}日` : "本月游戏"}</h2>{day && <button className="text-button" onClick={() => setDay(null)}>显示整月</button>}</div>{selected.length ? <div className="release-list">{selected.map((game) => <button key={game.id} onClick={() => onOpen(catalog.find((item) => item.id === game.parentId) || game)}><time>{new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric" }).format(new Date(`${game.releaseDate}T12:00:00`))}</time><div><strong>{game.title}</strong><span>{game.platforms.join(" · ") || "平台待确认"}</span></div><span className={`release-pill ${releaseState(game)}`}>{releaseLabels[releaseState(game)]}</span><Icon name="arrow"/></button>)}</div> : <EmptyState title="这段时间暂无记录" description="可以切换月份或平台；未定档作品仍可在发现页查看。" action={<button className="button" onClick={onUndated}>查看未定档游戏</button>}/>}</>;
}
export function NewsView({ onOpen }: { onOpen: (game: CatalogGame) => void }) {
  return <><div className="page-heading"><div><p className="eyebrow">NEWS & SOURCES</p><h1>情报与来源</h1><p>在官宣、访谈和时间表之间，保留每条信息的出处。</p></div><span className="muted">人工核验 {SNAPSHOT_DATE}</span></div><div className="news-list">{signals.map((signal) => <article key={signal.id}><div><span className="source-tag">{signal.kind}</span><time>{signal.date}</time></div><h2>{signal.title}</h2><p>{signal.detail}</p><a href={signal.sourceUrl} target="_blank" rel="noreferrer">{signal.sourceLabel}<Icon name="external"/></a></article>)}</div><div className="section-heading"><h2>精选游戏来源台账</h2><span>{curatedGames.length} 部</span></div><div className="source-list">{curatedGames.map((game) => <article key={game.id}><div><button className="text-button" onClick={() => onOpen(game)}>{game.title}</button><p>{game.source.evidence}</p><small>核验：{game.source.checkedAt}</small></div><a className="button" href={game.source.url} target="_blank" rel="noreferrer">{game.source.label}<Icon name="external"/></a></article>)}</div><div className="notice">年度目录来自 Wikipedia，图片与文字版权归各权利人。自动检索结果保留来源标签；个人评分只显示你实际填写的数值。</div></>;
}
function downloadFile(filename: string, text: string) { const url = URL.createObjectURL(new Blob([text], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function SettingsView({ account, cloudUser, library, onLibrary, storageError, clearError, theme, onTheme, scale, onScale, density, onDensity, feed, syncState, refresh, notify }: { account?: ReactNode; cloudUser?: string; library: Library; onLibrary: Dispatch<SetStateAction<Library>>; storageError: string; clearError: () => void; theme: string; onTheme: (value: string) => void; scale: number; onScale: (value: number) => void; density: string; onDensity: (value: string) => void; feed: CatalogFeed; syncState: string; refresh: () => Promise<void>; notify: (message: string) => void }) {
  const fileRef = useRef<HTMLInputElement>(null);
  async function importBackup(file?: File) {
    if (!file) return;
    try { if (file.size > 10 * 1024 * 1024) throw new Error("备份文件不能超过 10 MB。"); const entries = validateLibrary(JSON.parse(await file.text())); onLibrary((current) => { const merged = { ...current }; for (const [id, entry] of Object.entries(entries)) if (!current[id] || entry.updatedAt > current[id].updatedAt) merged[id] = entry; return merged; }); clearError(); notify(`已合并 ${Object.keys(entries).length} 条记录，保留较新的修改`); } catch (error) { notify(error instanceof Error ? error.message : "导入失败，请检查备份文件。"); } if (fileRef.current) fileRef.current.value = "";
  }
  function backup() { try { const data = JSON.stringify({ version: 2, exportedAt: new Date().toISOString(), entries: library }, null, 2); downloadFile(`release-signal-${localDate()}.json`, data); } catch { downloadFile(`release-signal-${localDate()}.json`, JSON.stringify({ version: 2, entries: library }, null, 2)); } }
  return <><div className="page-heading"><div><p className="eyebrow">PREFERENCES</p><h1>设置与数据</h1><p>调整阅读体验，保管好你的游戏记录。</p></div></div>{account}<section className="settings-panel"><h2>外观</h2><div className="setting-row"><div><strong>主题</strong><p>首次使用默认浅色，之后记住你的选择。</p></div><div className="segmented">{["light", "dark"].map((value) => <button className={theme === value ? "active" : ""} key={value} onClick={() => onTheme(value)} aria-pressed={theme === value}>{value === "light" ? "浅色" : "深色"}</button>)}</div></div><div className="setting-row"><div><strong>界面大小</strong><p>文字和控件同步缩放，布局自动调整。</p></div><label><span className="sr-only">界面缩放</span><select value={scale} onChange={(e) => onScale(Number(e.target.value))}>{[.9, 1, 1.1, 1.2, 1.35, 1.5].map((value) => <option key={value} value={value}>{Math.round(value * 100)}%</option>)}</select></label></div><div className="setting-row"><div><strong>卡片密度</strong><p>选择更宽松或更紧凑的目录。</p></div><div className="segmented">{["comfortable", "compact"].map((value) => <button key={value} className={density === value ? "active" : ""} aria-pressed={density === value} onClick={() => onDensity(value)}>{value === "comfortable" ? "舒适" : "紧凑"}</button>)}</div></div></section>
    <section className="settings-panel"><h2>我的数据</h2><div className="setting-row"><div><strong>{Object.keys(library).length} 条个人记录</strong><p>{cloudUser ? "账号游戏架保存在云端，本机另存编辑缓存。备份可用于离线保管和迁移。" : "本机模式：清除浏览器数据会移除记录。登录后可合并到云端，或导出备份。"}</p></div><span className="source-tag">{storageError ? "本机缓存异常" : cloudUser ? "账号游戏架" : "本机保存"}</span></div><div className="backup-actions"><button className="button primary" onClick={backup}><Icon name="download"/>导出当前备份</button>{storageError && <button className="button" onClick={() => { try { const raw = cloudUser ? localStorage.getItem(`release-signal-account-cache:${cloudUser}`) : localStorage.getItem(LIBRARY_KEY) || localStorage.getItem("release-signal-personal-v1"); if (raw) downloadFile(`release-signal-recovery-${localDate()}.json`, raw); else notify("浏览器没有可导出的原始记录"); } catch { notify("浏览器禁止读取存储，请导出当前备份"); } }}>导出原始记录</button>}<button className="button" onClick={() => fileRef.current?.click()}><Icon name="upload"/>导入并合并</button><input ref={fileRef} type="file" accept="application/json,.json" className="sr-only" onChange={(e) => void importBackup(e.target.files?.[0])}/></div><p className="muted">导入会合并记录；同一游戏保留更新时间更晚的一份。</p></section><section className="settings-panel"><h2>目录更新</h2><p>打开网站时刷新目录，页面使用期间每 30 分钟检查一次。外部来源暂时不可用时保留已收录内容。</p><button className="button" disabled={syncState === "loading"} onClick={() => void refresh()}><Icon name="refresh"/>{syncState === "loading" ? "正在更新…" : "立即更新目录"}</button><p className="muted">{feed.updatedAt ? `上次目录更新时间：${feed.updatedAt.replace("T", " ").slice(0, 19)} UTC` : "使用精选目录"}{syncState === "error" && " · 本次更新失败，已保留快照"}</p></section></>;
}
