import{readFile,writeFile}from'node:fs/promises';import{resolve}from'node:path';import{mergeCatalog}from'../app/lib/catalog.ts';
const out=resolve(process.env.CATALOG_OUTPUT||'public/data');const index=JSON.parse(await readFile(resolve(out,'index.json'),'utf8'));const discovery=JSON.parse(await readFile('work/series-discovery.json','utf8'));const byEntity=new Map(index.items.filter(ip=>ip.entityId).map(ip=>[ip.entityId,ip]));
const norm=s=>s.toLowerCase().replace(/\([^)]*\)|video games?|franchise|series|シリーズ|电子游戏|電子遊戲|系列/g,'').replace(/[^\p{L}\p{N}]/gu,'');const redirects={};
for(const ip of index.items){const e=discovery.entities[ip.entityId];for(const claim of e?.claims?.P8345||[]){const root=byEntity.get(claim.mainsnak?.datavalue?.value?.id);if(!root||root.id===ip.id||!ip.en||norm(ip.en)!==norm(root.en))continue;const keep=!ip.id.startsWith('wd-')?ip:root;const remove=keep===ip?root:ip;redirects[remove.id]=keep.id;keep.aliases=[...new Set([...keep.aliases,...remove.aliases])];keep.searchAliases=[...new Set([...(keep.searchAliases||[]),...(remove.searchAliases||[])])];}}
function canonical(id){const seen=new Set();while(redirects[id]&&!seen.has(id)){seen.add(id);id=redirects[id];}return id;}
const channels=new Map();for(const ip of index.items)channels.set(ip.id,JSON.parse(await readFile(resolve(out,'series',ip.id+'.json'),'utf8')));
for(const[from,to]of Object.entries(redirects)){const target=channels.get(canonical(to));target.games=mergeCatalog(target.games,channels.get(from).games);Object.assign(target.characters,channels.get(from).characters);}
// Re-evaluate after deduplication and remake classification, not just discovery.
index.items=index.items.filter(ip=>ip.id==='apothecary-diaries'||channels.get(ip.id).games.filter(g=>(!g.editionKind||g.editionKind==='original')&&g.declaredStatus==='released').length>=2);
index.items=index.items.filter(ip=>!redirects[ip.id]);const validIds=new Set(index.items.map(ip=>ip.id));for(const ip of index.items){ip.parentIds=[...new Set((ip.parentIds||[]).map(canonical))].filter(id=>id!==ip.id&&validIds.has(id));ip.childIds=[];const channel=channels.get(ip.id);for(const g of channel.games){g.ipIds=[...new Set((g.ipIds||[]).map(canonical))].filter(id=>validIds.has(id));g.subseriesIds=[...new Set((g.subseriesIds||[]).map(canonical))].filter(id=>g.ipIds.includes(id));}ip.gameCount=channel.games.length;ip.originalCount=channel.games.filter(g=>(!g.editionKind||g.editionKind==='original')&&g.declaredStatus==='released').length;await writeFile(resolve(out,'series',ip.id+'.json'),JSON.stringify(channel));}
for(const ip of index.items)ip.childIds=index.items.filter(c=>c.parentIds.includes(ip.id)).map(c=>c.id);
index.redirects={...index.redirects,...redirects};index.stats.channels=index.items.length;index.stats.works=new Set(index.items.flatMap(ip=>channels.get(ip.id).games.map(g=>g.entityId||g.id))).size;
const search=index.items.flatMap(ip=>channels.get(ip.id).games.map(g=>({id:g.id,names:[...new Set([g.title,g.originalTitle,...Object.values(g.names||{}).map(n=>n.text)])],ipIds:g.ipIds})));const unique=[...new Map(search.map(g=>[g.id,g])).values()];
await writeFile(resolve(out,'search.json'),JSON.stringify(unique));await writeFile(resolve(out,'index.json'),JSON.stringify(index));console.log(JSON.stringify({consolidated:Object.keys(redirects).length,channels:index.items.length,works:index.stats.works}));
